### ISSUE TITLE
'Search' isn't working, throws errors

### ISSUE THREAD

**Issue by aormsby** [muffinista/chatterbot#22]
I'm having a bit of a problem with the Search function in your Chatterbot. I just want to preface this issue with the fact that I know almost nothing about Ruby or Twitter's API, so if I've done something incredibly noobish it's because I'm a noob. Go easy on me.

I tried to do a basic search and reply using this example code in the readme:

```
search("'surely you must be joking'") do |tweet|
    reply "@#{tweet_user(tweet)} I am serious, and don't call me Shirley!", tweet
end
```

But I get this error every time:

```
/Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/twitter-5.8.0/lib/twitter/rest/response/raise_error.rb:17:in `on_complete': Missing or invalid url parameter. (Twitter::Error::Forbidden)
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request/multipart.rb:14:in `call'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/twitter-5.8.0/lib/twitter/rest/request/multipart_with_file.rb:18:in `call'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/twitter-5.8.0/lib/twitter/rest/client.rb:92:in `request'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/twitter-5.8.0/lib/twitter/rest/client.rb:63:in `get'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/twitter-5.8.0/lib/twitter/rest/search.rb:32:in `search'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/chatterbot-0.9.1/lib/chatterbot/search.rb:28:in `block in search'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/chatterbot-0.9.1/lib/chatterbot/search.rb:26:in `each'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/chatterbot-0.9.1/lib/chatterbot/search.rb:26:in `search'
    from /Users/WilyKit/.rvm/gems/ruby-2.1.3/gems/chatterbot-0.9.1/lib/chatterbot/dsl.rb:23:in `search'

```

Any ideas why I can't make a simple search? Posting tweets works just fine. Any help is appreciated.

**Comment by jeffdaley** [comment]
I'm still getting this error. Seems to be an issue with single/double quotes? 

I can search `"I am great"` but not `"I'm great"`;
I can search `"surely you must be joking"` but not `"'surely you must be joking'"`.
