### ISSUE TITLE
chatterbot-register failures

### ISSUE THREAD

**Issue by vcavallo** [muffinista/chatterbot#41]
after pasting the `API Key` and `API Secret` i get a raise on this line:

`/Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/oauth-0.5.0/lib/oauth/consumer.rb:217:in `token_request': 401 Authorization Required (OAuth::Unauthorized)`

I tried setting up a `yml` file following the manual instructions and then running a bot command (`tweet`, for instance) but that route also fails with this:

`/Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': Could not authenticate you. (Twitter::Error::Unauthorized)`

I feel like I've followed all the different auth strategies offered by the documentation and nothing has worked. Any suggestions?

**Comment by vcavallo** [comment]
update: I tried running `chatterbot-register` anew and setting up and entirely new app, being very careful to follow the instructions to the letter and copy/paste everything very carefully. I ended up with this error (full stacktrace this time)

```
/Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:29:in `build_authorize_url': undefined method `blank?' for nil:NilClass (NoMethodError)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:11:in `authorize_url'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/lib/chatterbot/ui.rb:33:in `get_oauth_verifier'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/lib/chatterbot/client.rb:160:in `login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/lib/chatterbot/client.rb:99:in `require_login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/bin/chatterbot-register:60:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/chatterbot-register:23:in `load'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/chatterbot-register:23:in `<main>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
/Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:29:in `build_authorize_url': undefined method `blank?' for nil:NilClass (NoMethodError)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:11:in `authorize_url'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/lib/chatterbot/ui.rb:33:in `get_oauth_verifier'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/lib/chatterbot/client.rb:160:in `login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/lib/chatterbot/client.rb:99:in `require_login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.1/bin/chatterbot-register:60:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/chatterbot-register:23:in `load'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/chatterbot-register:23:in `<main>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by muffinista** [comment]
I just ran through the process and it seems to have worked for me. I was able to register an app, authorize an account, and send a tweet. You might want to try waiting a little while and see if it works again for you (Twitter is a little flaky sometimes). Otherwise, can you put the code for your bot somewhere I can see it? You can put it in a gist/etc and email it to me at colin at muffinlabs dot com

I see too that the instructions are way out of date. I'm planning on working on that over the next few days.

**Comment by vcavallo** [comment]
I'll look into this more thoroughly tomorrow and post the code if necessary. One thing that occurs to me right now: I'm using ruby 2.3.0 but notice that the Travis CI builds only go up to 2.2.0. 
ah - I just saw the `ruby:head` build, using `2.3.0dev`. Ok maybe that's not it :)

**Comment by vcavallo** [comment]
Update: I tried from scratch just now, using the same steps you outlined above.
- ran `chatterbot-register`
- `Hit Enter to continue.`.... make a new app.
- pasted the 'API Key' and 'API Secret'. hit enter. then:

```
You need to authorize your bot with Twitter.

Please login to Twitter under the bot's account. When you're ready, hit Enter.

Your browser will open with the following URL, where you can authorize the bot.

/Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/oauth-0.5.0/lib/oauth/consumer.rb:217:in `token_request': 401 Authorization Required (OAuth::Unauthorized)
```

**Comment by muffinista** [comment]
OK, this is weird, and I have two main ideas to try:

1 - can you confirm that you're pasting the API key/secret from the right place and in the right order? I only ask this because when I ran through this I noticed how vague the wording was and I was confused myself. Just to be super clear, you want the keys from this section of the Twitter apps page:

![api keys](https://www.dropbox.com/s/e3ybu0mf1ofz621/Screenshot%202016-02-26%2015.10.07.png?dl=1)

2 - If that's not it, would you mind installing the preview release of chatterbot and seeing if it works there? It's not officially released yet, but I think you can install it like this:

```
gem install chatterbot --pre
```

**Comment by vcavallo** [comment]
1. confirmed, using API Key and Secret from the "Keys and Access Tokens" tab.
2. I switched to `--pre` and had the exact same result. FYI, I'm using bundler (getting the --pre version via `gem 'chatterbot', '2.0.0.pre'`). could that have anything to do with it?

Here's the contents of my `Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.4.0)
    buftok (0.2.0)
    chatterbot (2.0.0.pre)
      colorize (>= 0.7.3)
      launchy (>= 2.4.2)
      oauth (>= 0.4.7)
      twitter (= 5.14.0)
    colorize (0.7.7)
    diff-lcs (1.2.5)
    equalizer (0.0.11)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    http (0.6.4)
      http_parser.rb (~> 0.6.0)
    http_parser.rb (0.6.0)
    json (1.8.3)
    launchy (2.4.3)
      addressable (~> 2.3)
    memoizable (0.4.2)
      thread_safe (~> 0.3, >= 0.3.1)
    multipart-post (2.0.0)
    naught (1.1.0)
    oauth (0.5.0)
    rake (10.5.0)
    rspec (3.4.0)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
    rspec-core (3.4.3)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    simple_oauth (0.3.1)
    thread_safe (0.3.5)
    twitter (5.14.0)
      addressable (~> 2.3)
      buftok (~> 0.2.0)
      equalizer (~> 0.0.9)
      faraday (~> 0.9.0)
      http (~> 0.6.0)
      http_parser.rb (~> 0.6.0)
      json (~> 1.8)
      memoizable (~> 0.4.0)
      naught (~> 1.0)
      simple_oauth (~> 0.3.0)

PLATFORMS
  ruby

DEPENDENCIES
  chatterbot (= 2.0.0.pre)
  rake
  rspec (~> 3.0)

BUNDLED WITH
   1.11.2
```

**Comment by vcavallo** [comment]
I switched to ruby 2.2.1 and tried `chatterbot-register` got this error again:

```
You need to authorize your bot with Twitter.

Please login to Twitter under the bot's account. When you're ready, hit Enter.

Your browser will open with the following URL, where you can authorize the bot.

/Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:29:in `build_authorize_url': undefined method `blank?' for nil:NilClass (NoMethodError)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:11:in `authorize_url'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/ui.rb:40:in `get_oauth_verifier'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:192:in `login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:130:in `require_login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/bin/chatterbot-register:59:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/chatterbot-register:23:in `load'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/chatterbot-register:23:in `<main>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
/Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:29:in `build_authorize_url': undefined method `blank?' for nil:NilClass (NoMethodError)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/tokens/request_token.rb:11:in `authorize_url'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/ui.rb:40:in `get_oauth_verifier'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:192:in `login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:130:in `require_login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/bin/chatterbot-register:59:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/chatterbot-register:23:in `load'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/chatterbot-register:23:in `<main>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Then I set up this basic file:

```
# example.rb
require 'chatterbot/dsl'
tweet "Hello World!"
```

And ran `ruby example.rb`, which prompted with the regular "looks like you need to get an API key"... i went through those steps, pasted the keys, etc. got the same error on the next step:

```
You need to authorize your bot with Twitter.

Please login to Twitter under the bot's account. When you're ready, hit Enter.

Your browser will open with the following URL, where you can authorize the bot.

/Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/consumer.rb:217:in `token_request': 400 Bad Request (OAuth::Unauthorized)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/consumer.rb:136:in `get_request_token'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:166:in `request_token'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/ui.rb:40:in `get_oauth_verifier'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:192:in `login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:130:in `require_login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/tweet.rb:8:in `tweet'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/dsl.rb:121:in `tweet'
        from protocado-example.rb:2:in `<main>'
/Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/consumer.rb:217:in `token_request': 400 Bad Request (OAuth::Unauthorized)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/oauth-0.5.0/lib/oauth/consumer.rb:136:in `get_request_token'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:166:in `request_token'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/ui.rb:40:in `get_oauth_verifier'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:192:in `login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/client.rb:130:in `require_login'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/tweet.rb:8:in `tweet'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.2.1/gems/chatterbot-2.0.0.pre/lib/chatterbot/dsl.rb:121:in `tweet'
```
when I check the `example.yml` file, i see contents like this:

```
---
:consumer_key: IB3mn[hiddenhiddenhidden]
:consumer_secret: z2RJ2Our[hiddenhiddenhiddenhiddenhidden]
```

Interestingly, in _another_ iteration of these tests, I noticed the paste into the terminal looked a little weird and when i checked the `yml` file, the first entry was like this:

```
:consumer_key: "\tIB3mn[hiddenhiddenhidden]" 
```

with a tab character in front of it... I'm using tmux, perhaps it's somehow ruining the pasting. I'll try outside tmux.

**Comment by muffinista** [comment]
OK, it's actually really helpful that you are running with a Gemfile. It looks like the oauth gem was updated recently. Would you mind specifying a specific version in your Gemfile?

```
gem 'oauth', '~> 0.4.7'
```

I think that might fix the issue. There's an [open ticket](https://github.com/oauth-xx/oauth-ruby/issues/100) on the oauth gem that sounds at least a little related to this problem.

**Comment by muffinista** [comment]
I have a strong suspicion that this was the problem, and I've pushed a [new version of the gem](https://rubygems.org/gems/chatterbot/versions/1.0.2) to handle it. Hopefully that helps!

**Comment by vcavallo** [comment]
`gem 'chatterbot', '~> 1.0.2'` did the trick. Thanks so much!!

**Comment by vcavallo** [comment]
Hi again :)
Interestingly, running the exact same code on a different machine is giving me a different issue. 
Running the `tweet` test fails this way:

```
$ protocado-example.rb
/Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/ruby_http_parser.bundle (fatal)
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:1:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:5:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter.rb:26:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-2.0.0.pre/lib/chatterbot.rb:3:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-2.0.0.pre/lib/chatterbot/dsl.rb:1:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Users/vincentcavallo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from ./protocado-example.rb:4:in `<main>'
```

and running `chatterbot-status` fails like this:

```
$ chatterbot-status
/Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `require': incompatible library version - /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/ruby_http_parser.bundle (fatal)
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:1:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/streaming/connection.rb:1:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:5:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter/streaming/client.rb:5:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter.rb:26:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/twitter-5.14.0/lib/twitter.rb:26:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.2/lib/chatterbot.rb:3:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.2/lib/chatterbot.rb:3:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.2/bin/chatterbot-status:4:in `require'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/gems/chatterbot-1.0.2/bin/chatterbot-status:4:in `<top (required)>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/chatterbot-status:23:in `load'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/chatterbot-status:23:in `<main>'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/vincentcavallo/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

still using `1.0.2`. this is the same codebase as I used when closing the issue two days ago, pulled from git and testing after `bundle install`ing.

**Comment by vcavallo** [comment]
I've found that this error occurs on ruby 2.3.0 only. If I switch to (say) 2.2.1 everything works normally again. 

Unfortunately I'm not sure which ruby version I was running when everything worked for me a few days ago originally - I assume I was unknowingly using 2.2.1 and upon switching to a different computer I was (again unknowingly) using 2.3.0. Hopefully this helps you out a bit.

If I get some extra time today I'll see if I can investigate and submit a fixing pull request.

**Comment by muffinista** [comment]
That is definitely a strange bug, and I'm not able to reproduce it locally. My first guess is that maybe the gem was compiled for 2.2 and something is incompatible with 2.3? You might try uninstalling http_parser and reinstalling it.

Alternatively, I've got a v2.0 of the gem that I've been thinking about finally releasing. It's possible it will fix this problem for you if you want to give it a try. I think you can install it with:
```
gem install chatterbot --pre
```

There's a few things that aren't compatible with code from 1.0 bots though so it might not be an option for you.

**Comment by vcavallo** [comment]
Thanks
